### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Altenhh** [memimoe/GDBrowser-RW#3]
# API
- [ ] Documentation Page
#### Levels
 - - [ ] Level | `level/<ID>/`
 - - [ ] Searching | `search?query=<search-query>/`
 - - [ ] Leaderboards | `level/<ID>/leaderboards/`
#### Profile
 - - [ ] User | `profile/username-or-id/`
 - - [ ] Leaderboard | `leaderboard/` | Returns the top players leaderboard
 - - [ ] Comments and profile posts | `comments/level-or-userID/`
#### Account
 - - [ ] Commenting | `POST: comment/`
 - - [ ] Liking | `POST: like/`
#### Misc
 - - [ ] Level analysis | `analyze/<ID>/` | Returns some level objects data.
 - - [ ] Icons | `icon/<username>/`

# Website
- [ ] Credits
- [ ] Icon kit (probably not important)
- [ ] Footer
- [ ] Level card model
- [ ] Level listing page
- [ ] Saved Page
- [ ] Daily Page
- [ ] Weekly Page
- [ ] Gauntlets (this one you can prettify :muugu:)
- [ ] Hall of fame
- [ ] Map Packs
#### Leader board
- - [ ] User card
- - [ ] Top 250
- - [ ] Accurate
- - [ ] Creators
- - [ ] Info popup
#### Search
- - [ ] Text box
- - [ ] Filter buttons (most downloaded / trending / etc)
- - [ ] Difficulty Filter
- - [ ] Length filter
- - [ ] Rated filter
- - [ ] Advanced Filters
#### Level page
- - [ ] Save/Delete button
- - [ ] Level info (id / version / objects / etc)
##### Level analysis
- - - [ ] Object count
- - - [ ] Optimization count
- - - [ ] Portal order
- - - [ ] Portal filter
- - - [ ] Triggers
- - - [ ] Jump rings
- - - [ ] Block types
- - - [ ] Misc objs
- - - [ ] Level style
- - - [ ] Trigger groups use count
- - - [ ] Color channels
- - - [ ] Level data
##### Level comments
- - - [ ] Comment card
- - - [ ] Most liked
- - - [ ] Most recent
- - - [ ] Comment on level
##### Level Leader board
- - - [ ] Leader board card
- - - [ ] Top filter
- - - [ ] Week filter
